# Generated by Django 4.2.6 on 2024-01-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_stripe_price_id_product_stripe_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattachment',
            name='handle',
        ),
    ]
